ImportExcel/Models/ErrorViewModel.cs
namespace ImportExcel.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

ImportExcel/Models/HTMLModel.cs
namespace ImportExcel.Models
{
    public class HTMLModel
    {
        public List<string> Columns { get; set; }
        public List<OrderDTO> Orders { get; set; }
    }
}

ImportExcel/Controllers/HTMLController.cs
using DAL.Enums;
using DAL.Factory;
using DAL.Interface;
using ImportExcel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OfficeOpenXml.Style;
using System.Dynamic;

namespace ImportExcel.Controllers
{
    public class HTMLController : Controller
    {
        private readonly IExportFactory _exportFactory;
        public HTMLController(IExportFactory exportFactory)
        {
            _exportFactory = exportFactory;
        }
        public static List<SelectListItem> items;
        public IActionResult Index()
        {
            items = new List<SelectListItem>();
            SelectListItem selectListItem = new SelectListItem();
            selectListItem.Text = "Id";
            selectListItem.Value = "Id";
            items.Add(selectListItem);
            selectListItem = new SelectListItem();
            selectListItem.Text = "Image";
            selectListItem.Value = "Image";
            items.Add(selectListItem);
            selectListItem = new SelectListItem();
            selectListItem.Text = "Name";
            selectListItem.Value = "Name";
            items.Add(selectListItem);
            selectListItem = new SelectListItem();
            selectListItem.Text = "OrderDate";
            selectListItem.Value = "OrderDate";
            items.Add(selectListItem);
            selectListItem = new SelectListItem();
            selectListItem.Text = "Price";
            selectListItem.Value = "Price";
            items.Add(selectListItem);
            selectListItem = new SelectListItem();
            selectListItem.Text = "Discount";
            selectListItem.Value = "Discount";
            items.Add(selectListItem);
            return View();
        }

        [HttpGet]
        public IActionResult DesiredTable(HTMLModel model)
        {
            IFileExportRepository fileExport = _exportFactory.GetDataExporter(ExporterEnum.Database);
            model.Orders = fileExport.ExportData();
            List<IDictionary<string, object>> filteredOrders = model.Orders.Select(order =>
            {
                var filteredOrder = new ExpandoObject() as IDictionary<string, object>;

                foreach (var column in model.Columns)
                {
                    var property = typeof(OrderDTO).GetProperty(column);
                    if (property != null)
                    {
                        filteredOrder.Add(column, property.GetValue(order));
                    }
                }

                return filteredOrder;
            }).ToList();
            return View(filteredOrders);
        }
    }
}

ImportExcel/Controllers/HomeController.cs
using ImportExcel.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ImportExcel.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

ImportExcel/Controllers/OrderController.cs
using DAL.Enums;
using DAL.Factory;
using DAL.Interface;
using ImportExcel.Interface;
using Microsoft.AspNetCore.Mvc;

namespace ImportExcel.Controllers
{
    public class OrderController : Controller
    {
        private readonly IFileImportDBRepository _fileDBRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IExportFactory _exportFactory;
        private readonly IFileImportJsonRepository _fileJsonRepository;
        private readonly IUtility _utility;
        private readonly ILogger<OrderController> _logger;


        public static List<OrderDTO> orders;
        public OrderController(IFileImportDBRepository file, IWebHostEnvironment webHostEnvironment, IExportFactory exportFactory, ILogger<OrderController> logger, IFileImportJsonRepository fileImportJson, IUtility utility)
        {
            _fileDBRepository = file;
            _webHostEnvironment = webHostEnvironment;
            _exportFactory = exportFactory;
            _logger = logger;
            _fileJsonRepository = fileImportJson;
            _utility = utility;
        }

        [HttpGet]
        public IActionResult ImportData()
        {
            return View();
        }

        [HttpPost]
        public IActionResult UploadExcel(IFormFile inputFile)
        {
            _logger.LogInformation("Uploading file starting");
            if (inputFile == null || inputFile.Length == 0)
            {
                return BadRequest("File is empty");
            }
            string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "Json/orders.json");

            var orders = _utility.GetDataFromExcel(inputFile);
            _fileDBRepository.ImportToDatabase(orders);
            var count = _fileJsonRepository.ImportToJson(filePath, orders);
            TempData["TotalRecords"] = count + " Record Inserted";
            _logger.LogInformation(count + " Record Inserted");
            _logger.LogInformation("Uploading file end");
            return RedirectToAction(nameof(ImportData));
        }

        [HttpGet]
        public IActionResult ExportData()
        {
            return View();
        }

        [HttpPost]
        public void ExportData(ExporterEnum exporterType)
        {
            _logger.LogInformation("Export data starting");
            IFileExportRepository dataExporter = _exportFactory.GetDataExporter(exporterType);
            string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "Json/orders.json");
            orders = dataExporter.ExportData(filePath);
            _logger.LogInformation("Export data ending");
        }

        [HttpGet]
        public IActionResult OrderList()
        {
            _logger.LogInformation("Reading data starting");
            return View(orders);
        }

        [HttpGet]
        public void SearchData(string data)
        {
            orders = _fileDBRepository.SearchFromDatabase(data);
        }

        [HttpGet]
        public  IActionResult FilterData(DateTime startDate, DateTime endDate)
        {
            orders =  _fileDBRepository.FilterFromDatabase(startDate, endDate);
            return RedirectToAction(nameof(OrderList));
        }

    }
}

ImportExcel/Views/HTML/DesiredTable.cshtml
@model List<IDictionary<string, object>>  // Define the model as a list of dictionaries
<div class="container">
    <table id="myTable" class="table table-striped table-bordered">
        <thead>
            <tr>
                @foreach (var column in Model.FirstOrDefault()?.Keys ?? Enumerable.Empty<string>())
                {
                    <th>@column</th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model)
            {
                <tr>
                    @foreach (var value in order.Values)
                    {
                        if (value.ToString().EndsWith(".jpeg"))
                        {
                            <td><img src="@value" /></td>
                        }
                        else
                        {
                            <td>@value</td>
                        }
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            $("#myTable").tablesorter();
        });
    </script>
}

ImportExcel/Views/HTML/Index.cshtml
@model ImportExcel.Models.HTMLModel
@using ImportExcel.Controllers;

@{
    ViewData["Title"] = "Order List";
}
<form asp-controller="HTML" asp-action="DesiredTable" method="get">
    <div class="form-group">
        <select multiple id="htmlDropdown" asp-items="HTMLController.items" asp-for="Columns" class="form-select">
        </select>
    </div>
    <br />
    <input type="submit" class="btn btn-primary" />
</form>
@section Scripts
    {
    <script>
        $("#htmlDropdown").select2();
    </script>
}

ImportExcel/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ImportExcel/Views/Order/ExportData.cshtml
@using DAL.Enums
@{
    ViewData["Title"] = "Export";
}
@* <form method="post" enctype="multipart/form-data" asp-controller="Order" asp-action="ExportData"> *@
<div class="form-group">
    <select id="exporter" name="exporterType" class="form-control">
        <option value="">Select a Exporter</option>
        @foreach (var export in Enum.GetValues(typeof(ExporterEnum)))
        {
            <option value="@export">@export</option>
        }
    </select>
</div>
<br />
<button id="btnRead" class="btn btn-primary">Read Data</button>
@* </form> *@
<br />

@section Scripts{
    <script>
        $(document).ready(function () {
            $("#btnRead").click(function () {
                var exporterType = $("#exporter").val();
                $.ajax({
                    url: "/Order/ExportData",
                    method: "POST",
                    data: { exporterType: exporterType },
                    success: function (response) {
                        window.location.href = '@Url.Action("OrderList", "Order")'
                    }
                });
            });
        });
    </script>
}

ImportExcel/Views/Order/ImportData.cshtml
@{
    ViewData["Title"] = "Import";
}
<form method="post" enctype="multipart/form-data" asp-controller="Order" asp-action="UploadExcel">
    <div class="form-group">
        <label for="inputFile">Select Excel File:</label>
        <input type="file" accept=".xlsx" class="form-control" name="inputFile" id="inputFile" required />
    </div>
    <br />
        <button type="submit" class="btn btn-primary">Submit</button>
</form>
<br />
<label>@TempData["TotalRecords"]</label>

ImportExcel/Views/Order/OrderList.cshtml
@model List<OrderDTO>
@{
    ViewData["Title"] = "Order List";
}
<form method="get" asp-controller="Order" asp-action="FilterData">
<input name="startDate" type="date" />
<input name="endDate" type="date" />
<input type="submit" />
</form>
<div class="main-page">
    <div class="container-wrapper">
        <div class="header">
            <h1 class="header-heading">MY PURCHSES</h1>
            <div class="search-wrapper">
                <i class="fa fas fa-solid fa-magnifying-glass"></i>
                <input id="txtSearch" type="text" class="search-input">
            </div>
        </div>
        <div class="content-section">
            <div class="tabs-section">
                <div class="tab">To Pay</div>
                <div class="tab active">To Receive</div>
                <div class="tab">Completed</div>
                <div class="tab">Refund</div>
            </div>
            @foreach (var item in Model)
            {

            
            <div class="tabs-content">
                <div class="date-wrapper">
                    <p class="store-name">Vodus Store <i class="fa fa-solid fa-angle-right"></i></p>
                    <p class="date">Order Date:@item.OrderDate</p>
                </div>
                <div class="product-wrapper">
                    <div class="img-wrapper">
                        <img src="@item.Image" alt="">
                    </div>
                    <div class="product-detail d-flex justify-content-between align-items-end align-items-lg-center flex-column flex-lg-row">
                        <div class="d-flex flex-column flex-md-row product-text-content justify-content-between align-items-start align-items-md-center">
                            <div class="d-flex w-100 justify-content-between align-items-center">
                                <div class="d-flex flex-column justify-content-center">
                                    <p class="product-type">@item.Name</p>
                                    <p class="product-selection">RM5 DISCOUNT (50 VPoints) <i class="fa fa-solid fa-angle-down"></i></p>
                                    <p class="product-info">variation:Black, XL</p>
                                </div>
                                <div class="size-box mx-2 mx-lg-4">x1</div>
                            </div>
                            <div class="d-flex justify-content-between">
                                <p class="actual-price">@item.Price</p> <p class="discount-price">@item.Discount</p>
                            </div>
                        </div>
                        <div class="order-status-wrapper">Pending <i class="fa fa-solid fa-angle-right"></i></div>
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
</div>
@section Scripts
{
    <script>
        $('#txtSearch').keypress(function (e) {
            var key = e.which;
            if (key == 13)  // the enter key code
            {
                var data = $("#txtSearch").val();
                $.ajax({
                    url: "/Order/SearchData",
                    method: "GET",
                    data: { data: data },
                    success: function (response) {
                        window.location.href = '@Url.Action("OrderList", "Order")'
                    }
                });
            }
        });
    </script>
}

ImportExcel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ImportExcel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ImportExcel.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sample.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/css/theme.default.min.css">
    <link href="https://unpkg.com/@@fortawesome/fontawesome-free@6.1.2/css/all.css"
          rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ImportExcel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="ImportData">Import Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="ExportData">Export Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HTML" asp-action="Index">HTML Table</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ImportExcel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/js/jquery.tablesorter.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>